EPL/EPL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Caching;
using System.Web.Mvc;
using EPL.DataModel;
using EPL.Repository;
using EPL.Service;

namespace EPL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (HttpContext.Cache.Get("schedulers") == null)
            {
                HttpContext.Cache.Insert("schedulers", GetAllSchedules(), null, DateTime.Now.AddMinutes(1),
                    Cache.NoSlidingExpiration);
            }
            var schedulers = (List<Schedule>)HttpContext.Cache.Get("schedulers");
            var showingschedules = schedulers.Where(x => (x.Time - GetGmt8TimeNow()).TotalHours >= -2).ToList();
            var viewmodels = new ScheduleService().MapToViewModel(showingschedules);
            return View(viewmodels);
        }


        public ActionResult Videos()
        {
            if (HttpContext.Cache.Get("schedulers") == null)
            {
                HttpContext.Cache.Insert("schedulers", GetAllSchedules(), null, DateTime.UtcNow.AddSeconds(30),
                    Cache.NoSlidingExpiration);
            }
            var schedulers = (List<Schedule>)HttpContext.Cache.Get("schedulers");
            var pastMatches = schedulers.Where(x => (x.Time - GetGmt8TimeNow()).TotalHours < -2).OrderByDescending(x=>x.Time).ToList();
            var viewmodels = new ScheduleService().MapToViewModel(pastMatches.Where(x=>x.Time > new DateTime(1900,1,1)).ToList());
            return View(viewmodels);
        }
        private static DateTime GetGmt8TimeNow()
        {
            return TimeZoneInfo.ConvertTimeBySystemTimeZoneId(
                DateTime.UtcNow, "Singapore Standard Time");
        }

        private List<Schedule> GetAllSchedules()
        {
            var repo = new EplRepo();
            var schedules = repo.GetAllSchedule();
            return schedules;
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult TvShow()
        {
            var repo = new EplRepo();
            var tvshows = repo.GetAllTvShows();
            var viewmodels = new TvShowService().MapToViewModel(tvshows);
            return View(viewmodels);
        }

        public ActionResult Donate()
        {
            return View();
        }

        public ActionResult LinkPage(string url)
        {
            ViewBag.Message = url;
            return View();
        }

        public ActionResult Pending(string url)
        {
            ViewBag.Message = url;
            return View();
        }
        //public ActionResult Contact()
        //{
        //    ViewBag.Message = "Your contact page.";
        //    var repo = new EplRepo();
        //    var schedules = repo.GetAllSchedule();
        //    var viewmodels = new ScheduleService().MapToViewModel(schedules);
        //    return View(viewmodels);
        //}


        //public ActionResult AddSchedule()
        //{
        //    ViewBag.Message = "Your Add Schedule page.";

        //    return View();
        //}
    }
}

EPL/EPL/Controllers/ScheduleController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using EPL.DataModel;
using EPL.Repository;
using EPL.ViewModels;

namespace EPL.Controllers
{
    public class ScheduleController : Controller
    {
        public ScheduleController()
        {
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddSchedule(ScheduleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var schedule = new Schedule(model);
                var repo = new EplRepo();
                repo.UpSertSchedule(schedule);
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("About", "Home");
        }

     
    }
}

EPL/EPL/Views/Home/About.cshtml
@*@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>*@
<head>
    <script>

        function off() {
            document.getElementById("overlay").style.display = "none";
        }
    </script>

    <style>
     

        .overlay {
            position:fixed;
            top: 50%;
            left: 50%;
            width:250px;
            height:250px;
            margin-top: -125px; /*set to a negative number 1/2 of your height*/
            margin-left: -125px; /*set to a negative number 1/2 of your width*/
            background-color: rgba(0,0,0,0.5);
            cursor: pointer;
            z-index: 99;
            display: none;
        }
        .overlay .closebtn {
            position: absolute;
            top: 15px;
            right: 30px;
            font-size: 30px;
        }
    </style>
</head>
<body>
<div id="overlay" class="overlay">
<a href="javascript:void(0)" class="closebtn" onclick="off()">&times;</a>

    <script type="text/javascript">
        var ad_idzone = "2739748",
            ad_width = "250",
            ad_height = "250";
    </script>
    <script type="text/javascript" src="https://ads.exdynsrv.com/ads.js"></script>
    <noscript><a href="https://main.exdynsrv.com/img-click.php?idzone=2739748" target="_blank"><img src="https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=2739748&output=img&type=250x250" width="250" height="250"></a></noscript>
</div>
    
<script type="text/javascript">
    setTimeout(function(){document.getElementById("overlay").style.display = "block"},15*60*1000);
</script>

<div>
    <iframe src="http://pub.pptv.com/player/iframe/index.html?rcc_id=500W#w=1000&h=480&id=301209" style="border: 0; position: absolute; top: 50px; left: 0; right: 0; bottom: 0; width: 100%; height: 100%" target="_self" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" scrolling="no"></iframe>
</div>
@*<iframe width="560" height="315" src="http://nba.tmiaoo.com/n/100209800/p.html" frameborder="0" allowfullscreen></iframe>*@
</body>

EPL/EPL/Views/Home/AddSchedule.cshtml
@model EPL.ViewModels.ScheduleViewModel
@{
    ViewBag.Title = "AddSchdule";
}
<head>
    <script type="text/javascript">
    $('.datepicker').datepicker(); //Initialise any date pickers
    </script>
</head>

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("AddSchedule", "Schedule", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new schedule.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Id, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Id, new {@class = "form-control"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.HomeTeam, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.HomeTeam, new {@class = "form-control"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.AwayTeam, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.AwayTeam, new {@class = "form-control"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Time, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
           @Html.TextBoxFor(model => model.Time, new { @class = "form-control datepicker", placeholder = "Enter Drop-off date here..." })
           @Html.ValidationMessageFor(model => model.Time)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Link, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Link, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Add" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EPL/EPL/Views/Home/Contact.cshtml
@model EPL.ViewModels.ScheduleViewModelCollection
@{
    ViewBag.Title = "Home Page";
}
<head>
    @Styles.Render("~/Content/eplcss")
    @Styles.Render("~/Content/badge-abbreviations.css")
</head>


         @foreach (var keyvaluePair in Model.Collection)
         {
             <section class="fixtures">
                 <time class="date long" datetime=@Html.Raw(keyvaluePair.Key)><strong>@Html.Raw(keyvaluePair.Key)</strong></time>
                 <time class="date short" datetime=@Html.Raw(keyvaluePair.Key)><strong>@Html.Raw(keyvaluePair.Value.First().ShortEventDate)</strong></time>
                 <div data-competition-matches-list=@Html.Raw(keyvaluePair.Key)>
                     <div class="competition right"><span class="competitionImage1"></span><span class="competitionLabel1">Premier League</span></div>
                     <ul class="matchList">
                         @foreach (var list in keyvaluePair.Value)
                         {

                             <li class="matchFixtureContainer"
                                 data-home=@Html.Raw(list.HomeTeam) data-away=@Html.Raw(list.AwayTeam) data-competition="Premier League"
                                 data-venue=@Html.Raw(list.Stadium) data-comp-match-item="14173" data-comp-match-item-ko="1480768200000"
                                 data-comp-match-item-status="U">
                                 @if (!string.IsNullOrEmpty(list.Link))
                                 {
                                     <a data-template-rendered="" href=@Html.Raw(list.Link) class="fixture preMatch" data-matchid="14173">
                            
                                         <span class="overview">
                                             <span class="teams">
                                                 <span class="team"><span class="teamName">@Html.Raw(list.HomeTeam)</span><span class="badge-25 t@(@list.Homeid)"></span></span>
                                                 <time >@Html.Raw(list.KickOffTimeWithOutDate)</time>
                                                 <span class="team"><span class="badge-25 t@(@list.Awayid)"></span> <span class="teamName">@Html.Raw(list.AwayTeam) </span></span>
                                             </span>
                                             <span class="stadiumName"><span class="icn stadium"></span> @Html.Raw(list.Stadium)</span>
                                             <span class="broadcaster"></span> <span class="icn arrow-right"></span>
                                         </span>
                                     </a>
                 
                                     <span data-ui-modal="#quickviewModal" class="btn quickView" role="button">@Html.ActionLink("Watch Live", "LinkPage", "Home",new {url=@list.Link},null)</span>
                                 }
                                 else
                                 {
                                     <a data-template-rendered="" href="" class="fixture preMatch" data-matchid="14173">
                            
                                         <span class="overview">
                                             <span class="teams">
                                                 <span class="team"><span class="teamName">@Html.Raw(list.HomeTeam)</span><span class="badge-25 t@(@list.Homeid)"></span></span>
                                                 <time datetime="20:30">@Html.Raw(list.KickOffTimeWithOutDate)</time>
                                                 <span class="team"><span class="badge-25 t@(@list.Awayid)"></span> <span class="teamName">@Html.Raw(list.AwayTeam) </span></span>
                                             </span>
                                             <span class="stadiumName"><span class="icn stadium"></span> @Html.Raw(list.Stadium)</span>
                                             @*<span class="fixtureBroadcast broadcastDataContainer">
                                      <span class="broadcaster">Links   
                                         <span  class="logo broadcaster-SINGMIO" onclick="window.open('http://us.141592653589793238462643383.com/cs.html?id=qie786')"></span>
                                          <span class="logo broadcaster-SINGMIO" onclick="alert('abc')"></span>
                                      </span>  
                                    </span>*@
                                             <span class="icn arrow-right"></span>
                                         </span>
                                     </a>
                                     <span data-ui-modal="#quickviewModal" class="btn quickView" role="button">@Html.ActionLink("Link", "LinkPage", "Home",new {link=@list.Link})</span>
                                 }
                             </li>

                         }
                     </ul>
                 </div>
             </section>
         }
         

EPL/EPL/Views/Home/Donate.cshtml
@*@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>*@

<body>
<div>
    <h4>如果你喜欢这个网站，可以通过支付宝支持，金额多少无所谓，谢谢</h4>
    <img src="..\..\Image\pay.png" width="400" height="500"><img>
        </div>
</body>

EPL/EPL/Views/Home/Index.cshtml
@model EPL.ViewModels.ScheduleViewModelCollection
@{
    ViewBag.Title = "EPL Online";
}
<head>

    @Styles.Render("~/Content/eplcss")
    @Styles.Render("~/Content/badge-abbreviations.css")

</head>

<meta name="referrer" content="no-referrer" />
<body>
@foreach (var keyvaluePair in Model.Collection)
{
    <section class="fixtures">
        <time class="date long" datetime=@Html.Raw(keyvaluePair.Key)><strong>@Html.Raw(keyvaluePair.Key)</strong></time>
        <time class="date short" datetime=@Html.Raw(keyvaluePair.Key)><strong>@Html.Raw(keyvaluePair.Value.First().ShortEventDate)</strong></time>
        <div data-competition-matches-list=@Html.Raw(keyvaluePair.Key)>

            <div class="competition right"><span class="competitionImage1"></span><span class="competitionLabel1">Premier League</span>
            </div>
            <ul class="matchList">
                @foreach (var list in keyvaluePair.Value)
                {

                    <li class="matchFixtureContainer"
                        data-home=@Html.Raw(list.HomeTeam) data-away=@Html.Raw(list.AwayTeam) data-competition="Premier League"
                        data-venue=@Html.Raw(list.Stadium) data-comp-match-item=@Html.Raw(list.Id) data-comp-match-item-ko="1480768200000"
                        data-comp-match-item-status="U">
                        @if (!string.IsNullOrEmpty(list.Link))
                        {
                            <a data-template-rendered="" href=@Url.Action("LinkPage", "Home", new {url = @list.Link}, null) class="fixture preMatch" data-matchid=@Html.Raw(list.Id)>
                                <span class="overview" >
                                    <span class="teams">
                                        <span class="team"><span class="teamName">@Html.Raw(list.HomeTeam)</span><span class="badge-25 t@(@list.Homeid)"></span></span>
                                        <time >@Html.Raw(list.KickOffTimeWithOutDate)</time>
                                        <span class="team"><span class="badge-25 t@(@list.Awayid)"></span> <span class="teamName">@Html.Raw(list.AwayTeam) </span></span>
                                    </span>
                                    <span class="stadiumName"><span class="icn stadium"></span> @Html.Raw(list.Stadium)</span>
                                    <span class="broadcaster"></span> <span class="icn arrow-right"></span>
                                </span>
                            </a>

                            <span data-ui-modal="#quickviewModal" class="btn quickView" role="button">@Html.ActionLink("Watch Live", "LinkPage", "Home", new {url = @list.Link}, null)</span>
                        }
                        else
                        {
                            <a data-template-rendered="" href=@Url.Action("Pending", "Home", new {url = @list.Link}, null) class="fixture preMatch" data-matchid="14173">

                                <span class="overview">
                                    <span class="teams">
                                        <span class="team"><span class="teamName">@Html.Raw(list.HomeTeam)</span><span class="badge-25 t@(@list.Homeid)"></span></span>
                                        <time datetime="20:30">@Html.Raw(list.KickOffTimeWithOutDate)</time>
                                        <span class="team"><span class="badge-25 t@(@list.Awayid)"></span> <span class="teamName">@Html.Raw(list.AwayTeam) </span></span>
                                    </span>
                                    <span class="stadiumName"><span class="icn stadium"></span> @Html.Raw(list.Stadium)</span>
                                    @*<span class="fixtureBroadcast broadcastDataContainer">
                                      <span class="broadcaster">Links   
                                         <span  class="logo broadcaster-SINGMIO" onclick="window.open('http://us.141592653589793238462643383.com/cs.html?id=qie786')"></span>
                                          <span class="logo broadcaster-SINGMIO" onclick="alert('abc')"></span>
                                      </span>  
                                    </span>*@
                                    <span class="icn arrow-right"></span>
                                </span>
                            </a>
                            //<span data-ui-modal="#quickviewModal" class="btn quickView" role="button">@Html.ActionLink("Link", "LinkPage", "Home", new {link = @list.Link})</span>
                        }
                    </li>

                }
            </ul>
        </div>
    </section>
}



</body>
         

EPL/EPL/Views/Home/LinkPage.cshtml
@{
    ViewBag.Title = "Channels";
}
<meta name="referrer" content="no-referrer"/>
<head>
    <script>
        function resizeIframe(obj) {
            obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
        }
    </script>
    
    <script>

        function off() {
            document.getElementById("overlay").style.display = "none";
        }
    </script>

    <style> 
        .overlay { 
            position:fixed;
            top: 50%;
            left: 50%;
            width:250px;
            height:250px;
            margin-top: -125px; /*set to a negative number 1/2 of your height*/
            margin-left: -125px; /*set to a negative number 1/2 of your width*/
            background-color: rgba(0,0,0,0.5);
            cursor: pointer;
            z-index: 99
        }

        .overlay .closebtn {
            position: absolute;
            top: 15px;
            right: 30px;
            font-size: 20px;
        }
    </style>

</head>
<body>
  
    <div id="overlay" class="overlay">
            <script type="text/javascript">
                var ad_idzone = "2739746",
                    ad_width = "250",
                    ad_height = "250";
            </script>
            <script type="text/javascript" src="https://ads.exdynsrv.com/ads.js"></script>
            <noscript><a href="https://main.exdynsrv.com/img-click.php?idzone=2739746" target="_blank"><img src="https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=2739746&output=img&type=250x250" width="250" height="250"></a></noscript>
            <div id="button1" style="position: absolute;top: 15px; right: 30px;visibility: visible;"><span onmouseup="document.getElementById('overlay').style.display = 'none'"><span onmouseup="document.getElementById('html1').style.display = 'none'"><img src="~/Image/close.png" alt="" height="18" width="18"></span></span></div>
        </div>

        <script type="text/javascript">
            setTimeout(function(){document.getElementById("overlay").style.display = "block"},15*60*1000);
        </script>
<iframe src=@ViewBag.Message style="border: 0; position: absolute; top: 60px; left: 0; right: 0; bottom: 0; width: 100%; height: 100%" target="_self" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" scrolling="no">

    </iframe>

@*<script type="text/javascript">
    var exoOpts = {
        cat: '506',
        login: 'bodboy52',
        idzone_300x250: '2737334',
        idsite: '678304',
        preroll: {},
        pause: {},
        postroll: {},
        show_thumb: '1'
    };
</script>
<script type="text/javascript" src="https://ads.exdynsrv.com/invideo.js"></script>
<script type="text/javascript" src="https://ads.exdynsrv.com/ads.js"></script>
<noscript><a href="https://main.exdynsrv.com/img-click.php?idzone=2730660" target="_blank"><img src="https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=2730660&output=img&type=728x90" width="728" height="90"></a></noscript>
<script type="text/javascript">
    var ad_idzone = "2730662",
        ad_width = "468",
        ad_height = "60";
</script>*@
<div style="display: none">
<script type="text/javascript">
    var ad_idzone = "2730664",
        ad_width = "728",
        ad_height = "90";
</script>
<script type="text/javascript" src="https://ads.exdynsrv.com/ads.js"></script>
<noscript><a href="https://main.exdynsrv.com/img-click.php?idzone=2730664" target="_blank"><img src="https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=2730664&output=img&type=728x90" width="728" height="90"></a></noscript>
<script type="text/javascript" src="https://ads.exdynsrv.com/ads.js"></script>
<noscript><a href="https://main.exdynsrv.com/img-click.php?idzone=2730662" target="_blank"><img src="https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=2730662&output=img&type=468x60" width="468" height="60"></a></noscript>
</div>
</body>

EPL/EPL/Views/Home/Pending.cshtml
<head>
    @Styles.Render("~/Content/screen.css")
    @Styles.Render("~/Content/badge-abbreviations.css")
</head>

<main id="mainContent" tabindex="0">


<div class="wrapper col-12">
	
    <section class="standardArticle">

        <div class="socialShareSticky">
            <div class="socialShareHover articleShare">
                <div data-script="pl_social-share" data-widget="social-page-share" data-render="pagehover" data-body="About the Premier League"><div class="socialShareHover"><div class="socialShareBtn" role="button" tabindex="0" aria-haspopup="true"><div class="icn share"></div>Share</div><ul class="socialOptions" role="listbox"><li><div class="option whatsapp" role="option" tabindex="0" data-social-service="whatsapp"><span alt="" class="icn whatsapp-w"></span><span class="visuallyHidden">action.share.whatsApp</span></div></li><li><div class="option twitter" role="option" tabindex="0" data-social-service="twitter"><span alt="" class="icn twitter-w"></span><span class="visuallyHidden">Share on Twitter</span></div></li><li><div class="option facebook" role="option" tabindex="0" data-social-service="facebook"><span alt="" class="icn facebook-w"></span><span class="visuallyHidden">Share on Facebook</span></div></li><li><div class="option google" role="option" tabindex="0" data-social-service="google"><span alt="" class="icn google-w"></span><span class="visuallyHidden">Google +</span></div></li></ul></div></div>
            </div>
        </div>

        <div data-script="pl_editorial-lists" data-widget="video-list" class="articleImage">
            <img src="https://platform-static-files.s3.amazonaws.com/premierleague/photo/2016/06/13/8aa1b150-60c6-449f-beda-954c50e8bcb1/4794357.jpg" alt="Leicester manager Claudio Ranieri and captain Wes Morgan lift the PL trophy">
        </div>

        <h3 class="subHeader"> Please Come back to later before the match start</h3>


        <p class="copy">
        </p><p><strong>The link will be updated 10-30 mins before the match start</strong></p>
        <p><strong>直播链接会在比赛开始前10-30分钟更新</strong></p>
    
    </section>


</div>
</main>

EPL/EPL/Views/Home/VideoPage.cshtml
@*@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>*@
<meta name="referrer" content="no-referrer"/>
<head>
    <script>
        function resizeIframe(obj) {
            obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
        }
    </script>
</head>
<body>

<iframe src=@ViewBag.Message style="border: 0; position:absolute; top:50px; left:0; right:0; bottom:0; width:100%; height:100%" target="_self" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" scrolling="no">
    
</iframe>

    <script type="text/javascript" src="https://ads.exdynsrv.com/ads.js"></script>
    <noscript><a href="https://main.exdynsrv.com/img-click.php?idzone=2730660" target="_blank"><img src="https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=2730660&output=img&type=728x90" width="728" height="90"></a></noscript>
    <script type="text/javascript">
    var ad_idzone = "2730662",
        ad_width = "468",
        ad_height = "60";
    </script>
    <script type="text/javascript">
    var ad_idzone = "2730664",
        ad_width = "728",
        ad_height = "90";
    </script>
    <script type="text/javascript" src="https://ads.exdynsrv.com/ads.js"></script>
    <noscript><a href="https://main.exdynsrv.com/img-click.php?idzone=2730664" target="_blank"><img src="https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=2730664&output=img&type=728x90" width="728" height="90"></a></noscript>
    <script type="text/javascript" src="https://ads.exdynsrv.com/ads.js"></script>
    <noscript><a href="https://main.exdynsrv.com/img-click.php?idzone=2730662" target="_blank"><img src="https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=2730662&output=img&type=468x60" width="468" height="60"></a></noscript>
</body>